using Microsoft.EntityFrameworkCore.Migrations;
using NpgsqlTypes;

#nullable disable

namespace PostgreSearch.Migrations
{
    /// <inheritdoc />
    public partial class AutoGenerated : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<NpgsqlTsVector>(
                name: "SearchVector",
                table: "ArticleLocalizations",
                type: "tsvector",
                nullable: true,
                computedColumnSql: "CASE WHEN \"Language\" = 0 THEN to_tsvector('english', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", ''))WHEN \"Language\" = 1 THEN to_tsvector('ukrainian', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", '')) ELSE NULL END",
                stored: true,
                oldClrType: typeof(NpgsqlTsVector),
                oldType: "tsvector",
                oldComputedColumnSql: "CASE WHEN \"Language\" = 0 THEN to_tsvector('english', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", ''))WHEN \"Language\" = 1 THEN to_tsvector('ukrainian', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", '')) ELSE NULL END",
                oldStored: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<NpgsqlTsVector>(
                name: "SearchVector",
                table: "ArticleLocalizations",
                type: "tsvector",
                nullable: false,
                computedColumnSql: "CASE WHEN \"Language\" = 0 THEN to_tsvector('english', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", ''))WHEN \"Language\" = 1 THEN to_tsvector('ukrainian', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", '')) ELSE NULL END",
                stored: true,
                oldClrType: typeof(NpgsqlTsVector),
                oldType: "tsvector",
                oldNullable: true,
                oldComputedColumnSql: "CASE WHEN \"Language\" = 0 THEN to_tsvector('english', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", ''))WHEN \"Language\" = 1 THEN to_tsvector('ukrainian', coalesce(\"Title\", '') || ' ' || coalesce(\"Content\", '')) ELSE NULL END",
                oldStored: true);
        }
    }
}
